set(SkyrimScripting_CMake_Version 0.1.0)
set(SkyrimScripting_CMake_ModuleDir "${CMAKE_CURRENT_LIST_DIR}/SkyrimScripting")
include("${SkyrimScripting_CMake_ModuleDir}/common.cmake")
include("${SkyrimScripting_CMake_ModuleDir}/skyrim_mod.cmake")
include("${SkyrimScripting_CMake_ModuleDir}/copy_files_to_skyrim_mod_folder.cmake")
